### ISSUE TITLE
Integration broken after upgrade to 2022.6.7

### ISSUE THREAD

**Issue by ronaldt80** [GeorgeSG/philips_airpurifier_http#13]
Hi @GeorgeSG - your integration has worked without issue for over a year now.. that is, until this afternoon. After upgrading and restarting ha I suddenly got this error. It s almost as if the configured ip is no longer picked up. I checked the IP of the purifiers, unchanged. Also my ha settings are unchanged. Any thoughts, based on the below what might be happening here? Others with similar errors?

In the meantime I rolled back ha.. unfortunately no solution.

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/philips_airpurifier_http/fan.py", line 119, in async_setup_platform
    client = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/philips_airpurifier_http/fan.py", line 120, in <lambda>
    lambda: HTTPAirClient(config[CONF_HOST], False)
  File "/usr/local/lib/python3.9/site-packages/pyairctrl/http_client.py", line 108, in __init__
    self.load_key()
  File "/usr/local/lib/python3.9/site-packages/pyairctrl/http_client.py", line 156, in load_key
    self._get_key()
  File "/usr/local/lib/python3.9/site-packages/pyairctrl/http_client.py", line 119, in _get_key
    with urllib.request.urlopen(req) as response:
  File "/usr/local/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500:
```

**Comment by ronaldt80** [comment]
Hard boot of the airpurifier solved the issue. Sorry for the inconvenience - should have tried the oldest trick in the book first of course.
